### PR TITLE
ci: machine type from e1 to f1

### PR DESCRIPTION
**Pull request by d-goncalves**

### CODE REVIEW

**Comment by d-goncalves** [comment]
@OpsBotPrime merge on friday

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @d-goncalves, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 133d0de6f90d48fc261c8c453c86fd6d0e407243, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/ebd9f0f5-82e0-4fad-a789-556cb2831a1c?pipeline_id=8fe838d9-5c9b-4d80-bd32-c49590e4f748) started.

**Pull request merged**
