### PR TITLE
Do not check information_schema and pg_catalog for PrimaryKeyBigInt

### PR DESCRIPTION
**Pull request by SemMulder**
We should ignore `information_schema` and `pg_catalog` for PrimaryKeyBigInt

This is in line with the other checks. And otherwise we run into the following when running under PG16:

```
ISSUE #1: The table ‘pg_catalog.pg_attribute’ primary key (attnum) is of type ‘smallint’ instead of ‘bigint’.
  If you do not solve this issue, you will encounter the following problems:
    • PostgreSQL's smallint type is 2 bytes. It is relatively easy to run out of values.
  You can solve this issue by taking one of the following measures:
    • Change the type of ‘pg_catalog.pg_attribute.attnum’ to ‘bigint’, as well as its associated auto generating sequence if it exists.
    • Silence this issue: ‘silence primary_key_bigint pg_catalog pg_attribute attnum’.
    • Silence this check: ‘silence primary_key_bigint’.
```

### CODE REVIEW

**Comment by SemMulder** [comment]
Tested this locally, indeed resolves the mentioned issue.

**Review by franciscoreinolds — APPROVED** [review]
lgtm, thanks for noticing this and picking it up!

**Comment by OpsBotPrime** [comment]
Rebased as 120b61980d821b38df3b37abbf55c45463596ca3, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/8689b032-53c4-479c-b0d1-30442e081a29?pipeline_id=b8ec41ad-033e-46b2-834f-f8cbab23b93d) started.

**Pull request merged**
